[package]
name = "readpe"
version = "0.1.0"
authors = ["3ts75"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
app = "0.6.5"
clap = "2.33.0"